
export {default as Box} from './Box/Box.jsx' 
export {default as Logo} from './Logo/Logo.jsx'
export {default as NavBar} from './NavBar/NavBar.jsx'
export {default as BgChanger} from './BgChanger/BgChanger.jsx'
export {default as Slider } from './Slider/Slider.jsx'
export {default as SliderPromo} from './SliderPromo/SliderPromo.jsx'
export {default as Category} from './Category/Category.jsx'
export {default as Blog} from './Blog/Blog.jsx'
export {default as ShippingIcon } from './ShippingIcon/ShippingIcon.jsx'
export {default as IconRedes} from './IconRedes/IconRedes.jsx'
export {default as CartIcon} from'./CartIcon/CartIcon.jsx'
